### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by rashid-adobe** [adobe/aem-core-cif-components#984]
I am unable to build the project in my local machine with fresh clone. When I am running `mvn clean install` then I'm getting below error. Could someone look and help me to fix this.
### Actual Behaviour
```
 --- frontend-maven-plugin:1.12.1:npm (npm-webpack-development) @ core-cif-react-components ---
[INFO] Running 'npm run webpack:dev' in C:\git\aem-core-cif-components\react-components
[INFO]
[INFO] > @adobe/aem-core-cif-react-components@2.12.2 webpack:dev C:\git\aem-core-cif-components\react-components
[INFO] > npm run i18n:extract-compile && webpack --mode=development
[INFO]
[INFO]
[INFO] > @adobe/aem-core-cif-react-components@2.12.2 i18n:extract-compile C:\git\aem-core-cif-components\react-components
[INFO] > formatjs extract --out-file i18n/__temp.json 'src/**/*.js' && formatjs compile --ast --out-file i18n/en.json i18n/__temp.json && rm i18n/__temp.json
[INFO]
[INFO] 'rm' is not recognized as an internal or external command,
[INFO] operable program or batch file.
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! @adobe/aem-core-cif-react-components@2.12.2 i18n:extract-compile: `formatjs extract --out-file i18n/__temp.json 'src/**/*.js' && formatjs compile --ast --out-file i18n/en.json i18n/__temp.json && rm i18n/__temp.json`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR!
[INFO] npm ERR! Failed at the @adobe/aem-core-cif-react-components@2.12.2 i18n:extract-compile script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\mohammadr\AppData\Roaming\npm-cache\_logs\2023-07-31T07_23_39_564Z-debug.log
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! @adobe/aem-core-cif-react-components@2.12.2 webpack:dev: `npm run i18n:extract-compile && webpack --mode=development`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR!
[INFO] npm ERR! Failed at the @adobe/aem-core-cif-react-components@2.12.2 webpack:dev script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO]
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     C:\Users\mohammadr\AppData\Roaming\npm-cache\_logs\2023-07-31T07_23_39_579Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for AEM CIF Core Components - Reactor 2.12.3-SNAPSHOT:
[INFO]
[INFO] AEM CIF Core Components - Parent ................... SUCCESS [  0.910 s]
[INFO] AEM CIF Core Components - Content Package for React Components FAILURE [  9.645 s]
[INFO] AEM CIF Core Components - Core Bundle .............. SKIPPED
[INFO] AEM CIF Core Components - Content Package for apps . SKIPPED
[INFO] AEM CIF Core Components - Content Package for config SKIPPED
[INFO] AEM CIF Core Components - Examples Bundle .......... SKIPPED
[INFO] AEM CIF Core Components - Examples Frontend ........ SKIPPED
[INFO] AEM CIF Core Components - Examples Application Package SKIPPED
[INFO] AEM CIF Core Components - Examples Config Package .. SKIPPED
[INFO] AEM CIF Core Components - Examples Content Package . SKIPPED
[INFO] AEM CIF Core Components - Examples All Package ..... SKIPPED
[INFO] AEM CIF Core Components - Examples Reactor ......... SKIPPED
[INFO] AEM CIF Core Components - Products Recommendations Content Package SKIPPED
[INFO] AEM CIF Core Components - Products Recommendations React Components SKIPPED
[INFO] AEM CIF Core Components - Products Recommendations Bundle SKIPPED
[INFO] AEM CIF Core Components - Products Recommendations Reactor SKIPPED
[INFO] AEM CIF Core Components - Experience Platform Connector SKIPPED
[INFO] AEM CIF Core Components - All ...................... SKIPPED
[INFO] AEM CIF Core Components - Integration Tests Content Package SKIPPED
[INFO] AEM CIF Core Components - Integration Tests ........ SKIPPED
[INFO] AEM CIF Core Components - UI Tests ................. SKIPPED
[INFO] AEM CIF Core Components - Reactor .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.471 s
[INFO] Finished at: 2023-07-31T12:53:39+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npm (npm-webpack-development) on project core-cif-react-components: Failed to run task: 'npm run webpack:dev' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :core-cif-react-components
```

#### Platform and Version
I am using below versions:

- Node: v14.19.0
- NPM: 6.14.16
- Maven: 3.8.6

#### Logs taken while reproducing problem
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\git\\aem-core-cif-components\\frontend-maven-plugin\\node\\node.exe',
1 verbose cli   'C:\\git\\aem-core-cif-components\\frontend-maven-plugin\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'webpack:dev'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prewebpack:dev', 'webpack:dev', 'postwebpack:dev' ]
5 info lifecycle @adobe/aem-core-cif-react-components@2.12.2~prewebpack:dev: @adobe/aem-core-cif-react-components@2.12.2
6 info lifecycle @adobe/aem-core-cif-react-components@2.12.2~webpack:dev: @adobe/aem-core-cif-react-components@2.12.2
7 verbose lifecycle @adobe/aem-core-cif-react-components@2.12.2~webpack:dev: unsafe-perm in lifecycle true
8 verbose lifecycle @adobe/aem-core-cif-react-components@2.12.2~webpack:dev: PATH: C:\git\aem-core-cif-components\frontend-maven-plugin\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\git\aem-core-cif-components\react-components\node_modules\.bin;C:\git\aem-core-cif-components\frontend-maven-plugin\node;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk-11.0.16.1;C:\apache-maven-3.8.6\bin;C:\Users\mohammadr\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\Users\mohammadr\AppData\Local\Microsoft\WindowsApps;C:\Users\mohammadr\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Java\jdk-11.0.16.1;C:\apache-maven-3.8.6\bin;C:\Users\mohammadr\AppData\Local\GitHubDesktop\bin;C:\Users\mohammadr\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\mohammadr\AppData\Roaming\npm;C:\Program Files\heroku\bin;C:\wget-1.21.3-win64;;
9 verbose lifecycle @adobe/aem-core-cif-react-components@2.12.2~webpack:dev: CWD: C:\git\aem-core-cif-components\react-components
10 silly lifecycle @adobe/aem-core-cif-react-components@2.12.2~webpack:dev: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run i18n:extract-compile && webpack --mode=development'
10 silly lifecycle ]
11 silly lifecycle @adobe/aem-core-cif-react-components@2.12.2~webpack:dev: Returned: code: 1  signal: null
12 info lifecycle @adobe/aem-core-cif-react-components@2.12.2~webpack:dev: Failed to exec webpack:dev script
13 verbose stack Error: @adobe/aem-core-cif-react-components@2.12.2 webpack:dev: `npm run i18n:extract-compile && webpack --mode=development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\git\aem-core-cif-components\frontend-maven-plugin\node\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\git\aem-core-cif-components\frontend-maven-plugin\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @adobe/aem-core-cif-react-components@2.12.2
15 verbose cwd C:\git\aem-core-cif-components\react-components
16 verbose Windows_NT 10.0.19045
17 verbose argv "C:\\git\\aem-core-cif-components\\frontend-maven-plugin\\node\\node.exe" "C:\\git\\aem-core-cif-components\\frontend-maven-plugin\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "webpack:dev"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error @adobe/aem-core-cif-react-components@2.12.2 webpack:dev: `npm run i18n:extract-compile && webpack --mode=development`
22 error Exit status 1
23 error Failed at the @adobe/aem-core-cif-react-components@2.12.2 webpack:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by LSantha** [comment]
The solution is available in CIF Components 2.18.0 .
